// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDocumentList():Promise<Array<main.DocumentSummaryDto>>;

export function GetReferences(arg1:string):Promise<Array<main.DocumentReferenceDto>>;

export function LoadJournalToday():Promise<main.DocumentDto>;

export function OpenDocument(arg1:string):Promise<main.DocumentDto>;

export function OpenDocumentByTitle(arg1:string):Promise<main.DocumentDto>;

export function SaveDocument(arg1:main.DocumentDto):Promise<void>;

export function SearchDocuments(arg1:string):Promise<Array<main.DocumentSummaryDto>>;
