// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewDocument(arg1) {
  return window['go']['main']['App']['CreateNewDocument'](arg1);
}

export function GetDocumentList() {
  return window['go']['main']['App']['GetDocumentList']();
}

export function LoadJournalToday() {
  return window['go']['main']['App']['LoadJournalToday']();
}

export function OpenDocument(arg1) {
  return window['go']['main']['App']['OpenDocument'](arg1);
}

export function OpenDocumentByTitle(arg1) {
  return window['go']['main']['App']['OpenDocumentByTitle'](arg1);
}

export function SaveDocument(arg1) {
  return window['go']['main']['App']['SaveDocument'](arg1);
}

export function SearchDocuments(arg1) {
  return window['go']['main']['App']['SearchDocuments'](arg1);
}
