// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {main} from '../models';

export function LoadJournal(arg1:time.Time):Promise<main.DocumentDto>;

export function LoadJournalsFromTo(arg1:time.Time,arg2:time.Time):Promise<Array<main.DocumentDto>>;

export function LoadTodayDocument():Promise<main.DocumentDto>;

export function SaveDocument(arg1:main.DocumentDto):Promise<void>;

export function SetParagraphContent(arg1:string,arg2:string):Promise<string>;
